import { pgTable, text, timestamp, jsonb, boolean } from "drizzle-orm/pg-core";

export const retrospectives = pgTable("retrospectives", {
  id: text("id").primaryKey(), // UUID generated by client or server
  owner_id: text("owner_id").notNull(), // Future Auth UID
  slug: text("slug").notNull().unique(),
  status: text("status").notNull().default("draft"), // "draft" or "published"
  title: text("title"),
  couple_name: text("couple_name"),
  person_1: text("person_1"),
  person_2: text("person_2"),
  relationship_date: text("relationship_date"),
  cover_image: text("cover_image"),
  data: jsonb("data"), // Complete APP_DATA structure for backward compatibility
  theme: jsonb("theme"),
  created_at: timestamp("created_at").defaultNow(),
  updated_at: timestamp("updated_at").defaultNow(),
  published_at: timestamp("published_at"),
});
